README.md
app/Services/MailHog.php
app/Services/Mailhog.php

It installs [MailHog](https://github.com/mailhog/MailHog)
Using [Valet Proxy](https://laravel.com/docs/master/valet#proxying-services) you can add a custom domain to MailHog.
```
valet proxy mailhog http://127.0.0.1:8025
```
Now you can use http://mailhog.test

Add MailHog Service

---

app/Services/MariaDB.php

This adds MariaDB as an alternative to MySQL.
- Website: https://mariadb.org
- Docker image: https://hub.docker.com/_/mariadb
~~I guess it may be worth thinking about https://github.com/tightenco/takeout/issues/53 before merging though, as I think this affects MariaDB as well.~~ 🤔 Looks like MariaDB advise against it though: https://mariadb.com/kb/en/authentication-plugin-mysql_native_password
Actually, it looks like this isn't necessary in PHP `~7.1.16 || >=7.2.4` as it was updated to support it and Takeout requires `^7.2.5`. 👍🏻

feat: add MariaDB service

---

app/Commands/DisableCommand.php
app/Commands/EnableCommand.php

- Official dependencies names displayed instead of their class names (No more visual confusion between MsSql & MySql)
- Line break to separate the exit menu item from the rest
- Padding around the menu to help the text breathe
I think the UI would be awesome with greater vertical padding around the menu items text.
I haven't found a way to do so.
Any suggestion?

Command UI improvement proposal

---

README.md
app/Commands/HelpCommand.php
app/Commands/RestartCommand.php
app/Commands/StartCommand.php
app/Commands/StopCommand.php
app/Shell/Docker.php

Add commands for users that are not familiar with docker to start a stopped container as well as stop a running container.
issue #68

Add command to restart stopped containers and stop running containers

---

README.md
app/Services/DynamoDB.php

This PR had service for DynamoDB.
I used [cnadiminti/dynamodb-local](https://hub.docker.com/r/cnadiminti/dynamodb-local) docker image instead of official one from amazon [amazon/dynamodb-local](https://hub.docker.com/r/amazon/dynamodb-local) because the amazon image uses in memory db and is not configurable. In order to use a volume for the database with official image we should override the image command.

Add DynamoDB service

---

app/Services/Minio.php

This PR fixes several bugs with running Minio
1) The organization was missing causing the command to fail
2) The default keys were too short (Minio requires 8+ characters)
3) The command was missing `server /data` as outlined [here](https://hub.docker.com/r/minio/minio/)
These fixes should construct the proper command to run the docker image
`docker run -p 9000:9000 -e MINIO_ACCESS_KEY=minioadmin -e MINIO_SECRET_KEY=minioadmin -v minio_data:/data minio/minio:latest server /data`

Fix Minio run command

---

app/Services/Minio.php

Just added the \ to fix the minio run command.

Fixing minio run template bug '\'

---

app/Commands/ListCommand.php

This PR adds a JSON output option to the `takeout list` command.
If one would want to build a Desktop application for Takeout, this could be pretty handy 👀

Add JSON output option to container list

---

app/Services/MySql.php

The alternative is to edit the user after the container is created but that’s less than ideal. This should “just work” out of the box when the user is using an older PHP version.
I opted to not do detection because it's possible that the PHP version connecting to MySQL is different than the one used to start the container (e.g. if you're using takeout on the host machine + an older homestead box)
fixes #53

Fix MySQL default auth for PHP < 7.4

---

app/Services/MySql.php

Allow empty MySQL password

---

app/Commands/DisableCommand.php
app/Commands/EnableCommand.php
tests/Feature/EnableCommandTest.php

Something @loganhenson said got me thinking about making it even smoother to spin multiple services up at once, so just PRing this as an idea. Before:
```bash
takeout enable meilisearch
takeout enable beanstalkd
```
After:
```bash
takeout enable meilisearch beanstalkd
```
I installed docker and manually tested this a bit and it works great, but I only really explored the happy path. I'm pretty sure this would still play nicely with other options or flags being passed to `enable` if that were added at some point.

Allow enabling/disabling multiple services at once

---

app/Shell/Docker.php

Hi @mattstauffer, i found and fix this:

Return right container name when a docker run fail.

---

README.md

This may seems like a trivial detail, but for someone who isn't familiar with compiling a build this might save them some time.  It wasn't abundantly clear to me that you should prefix the two steps in build instructions with `php `.  Thanks for your time and consideration.

Update build instructions in readme to be more explicit

---

app/Commands/EnableCommand.php
app/Services.php
app/Services/BaseService.php
app/Services/Beanstalkd.php
app/Services/Category.php
app/Services/DynamoDB.php
app/Services/ElasticSearch.php
app/Services/InfluxDB.php
app/Services/MailHog.php
app/Services/MariaDb.php
app/Services/MeiliSearch.php
app/Services/Memcached.php
app/Services/Minio.php
app/Services/Mongo.php
app/Services/MsSql.php
app/Services/MySql.php
app/Services/PostgreSql.php
app/Services/Redis.php

Group the services list by categories

---

README.md

Adds the status of github actions to README.md.

Add github actions status to README.md

---

app/Commands/DisableCommand.php
app/Commands/EnableCommand.php
app/Services/BaseService.php
app/Shell/Environment.php
tests/Feature/BaseServiceTest.php
tests/Feature/DisableCommandTest.php
tests/Feature/EnableCommandTest.php
tests/Feature/EnvironmentTest.php
tests/Feature/ServiceEnableDefaultTest.php

I have worked out on using --default on any enable command to use default ports and tags or keys
can be useful if you create many services at once as per your project setup
#130 
I have edited the Environment.php to check ports availability on Linux and WSL
And I have edited the container name, so that it will not conflict when creating 2 docker container with same version but with different ports

Using --default option

---

app/Commands/EnableCommand.php

HI @josecanhelp  this morning after your merge we can't build takeout because there isn't Str import on EnableCommand.

Missing Str import on EnableCommand

---

app/Services/Sftp.php

Adds SFTP server support.  Does not allow direct outside communication on it's own but this could be accomplished via firewall policies/port forwarding.
Allows mapping of a local directory, a volume, or neither, via a prompt.  Related to #165

Add SFTP server support

---

app/Services/BaseService.php

Fix tag retrieval for Redis
Closes #177
Tag for redis is not a semver string, but "buster", as in underlying debian version

Fix tag retrieval for Redis

---

app/Services/ElasticSearch.php

Just a typo in Elasticsearch display name

Ucfirst of Elasticsearch display name

---

src/commands/list.ts
src/misc/interfaces.ts
src/shell/docker.ts
src/types.ts

Typescript convention uses `types.ts` to store interfaces.
I thought using `DockerContainer` instead of `Container` would make our code more easily readable.

Use more specific term for interface and rename types file

---

app/Services/Category.php
app/Services/Expose.php

Add Expose server support.
Adds a new category "Tools" to the `enable` menu.
Requires some external setup to get fully working:
- Wildcard DNS entry for Expose domain
- Reverse proxy or port forward to host from which takeout is running
Additional info in issue #166

Add Expose service

---

app/Commands/HelpCommand.php
app/Commands/LogCommand.php
app/Shell/Docker.php

For lazy people a new log command.

Add container log command.

---

app/Services/RabbitMQ.php

Adds RabbitMQ as a service. This is an available feature on Laravel Homestead and one I use for my development, so I'd like to see it available in Takeout if possible!
Notes:
- RabbitMQ relies on the hostname to organize data, so it's important we specify the hostname (-h option, comes from [RabbitMQ docker docs](https://hub.docker.com/_/rabbitmq))
- The default `latest` tag does not enable the management plugin, so opening/asking about the management port is unnecessary. I didn't know any way to conditionally ask for a management port based on the tag selected, so I overrode the default prompts so that `management` is the suggested default tag. Not sure if that's bad form 😂
Thanks for considering this! Love Takeout and how easy it makes using Docker in my dev workflow!

Add RabbitMQ service

---

README.md
app/Commands/DisableCommand.php
app/Commands/EnableCommand.php
app/Commands/StartCommand.php
app/Commands/StopCommand.php
app/Services/BaseService.php
app/Shell/Docker.php
app/Shell/DockerFormatter.php
app/Shell/Environment.php
tests/Feature/BaseServiceTest.php
tests/Feature/DisableCommandTest.php
tests/Feature/EnableCommandTest.php
tests/Feature/StartCommandTest.php
tests/Feature/StopCommandTest.php

References #146
I made a comment in the issue referenced above that gives a fairly detailed outline of changes made.  Please review that and my code and let me know what you would like for me to adjust.  I am sure there are probably better ways to code some of the array items.  Also, I extracted some code into private method where I thought it made sense.  Hopefully it readable.
I have manually tested all of the menus in native Windows 10.  I also manually tested the default menu system from the WSL prompt just to be sure my refactoring didn't break anything.  
I was reviewing the tests and noticed the default menu UI is not currently tested.  I think I could probably write a OS specific test to test the Windows menu.  Let me know if you want that to be included in this PR or just make a …

Add menu support for native Windows

---

.github/workflows/run-tests.yml

Closes #205 
This PR adds a matrix entry to also test `takeout` on Apple Silicon, this way all platforms that `takout` is probably going to be run on are covered.

Add matrix entry for Apple Silicon

---

README.md
app/Commands/HelpCommand.php
app/Commands/StartCommand.php

This will allow us to start all containers at once without pressing enter 5 times or even add it to our .bash_profile so that they start automatically when opening the command line.

Add --all in start command

---

tests/Feature/MicrosoftDockerTagsTest.php
tests/support/MicrosoftDockerTagsFakestream.php

Fixes the below error during `composer install`
```
Class Tests\Feature\MicrosoftDockerTagsFakestream located in ./tests/support/MicrosoftDockerTagsFakestream.php does not comply with psr-4 autoloading standard. Skipping.
```

Fixes PSR-4 issues

---

app/Services/MailDev.php

this PR adds the MailDev service as an alternative to MailHog.
why is MailDev MegaCool™?
1. when you get a new email you're getting updated directly in the tab title
2. MailDev has some PrettyCool™ features like responsive view, see email as text, etc
might be worth adding some competition to MailHog. who knows.

add MailDev service

---

app/Commands/StartCommand.php
app/Commands/StopCommand.php

This should resolve issue #211.  Apparently my original implementation to close the start and stop command menu if only the exit item remained did not work for the default menu layout.  This has been reworked and now works as intended.

Fix start and stop command bug where default menu closes early

---

README.md
src/services/mysql.ts
src/shell/environmentshell.ts

- Adds the port availability check for the MySQL service. I think this is something we could extract (to a validators folder?) so we could reuse in other services
- Adds a mention to install the `netstat` CLI tool if it's not already installed by default in the distro (mine wasn't)

Adds port availability check for the MySQL service

---

app/Shell/DockerTags.php
tests/Feature/DockerTagsTest.php

- Fix the `DockerTagsTest` because the API response changed from the DockerHub API
---
Not sure if this is the most "correct" fix, though.

Fix docker tags API response changed

---

app/Services/Minio.php

Hello, by default, MinIO Console is listening on a dynamic port that is randomly generated in every run, which makes it impossible to log in.
> WARNING: Console endpoint is listening on a dynamic port (42055), please use --console-address ":PORT" to choose a static port.
https://docs.min.io/docs/minio-docker-quickstart-guide.html

Add a static port for the MinIO Console.

---

app/Shell/DockerTags.php
tests/Feature/DockerTagsTest.php

Docker Hub paginates the tag list page and in order to pull the full list of tags, we would need to authenticate, which I've been trying to avoid for complexity sake. Luckily, we can expand the `page_size` parameter and bump it up to read more tags without needing to authenticate.
The next step to my solution is to partition the named tags and the numerical tags. We can rely on the higher numerical tags to be the "actual latest" tags and we can ignore the named tags when takeout is searching for "actual latest".

Fix "latest" tag fallback

---

.github/workflows/run-tests.yml
tests/Feature/DockerTagsTest.php

These issues will only show up in tests, so they don't need to be real constrains in `composer.json`

Constrain GuzzleHTTP/PSR7 in GH Actions to avoid return type issues

---

app/Services/BaseService.php

As described in #236 you sometimes want to use non-standard docker images because they have some plugins bundled you may want to use. Especially for PostgreSQL there are a lot of plugins not available in core, the most common is the PostGIS extension.
Instead of simply specifying a simple docker tag in the dialog you can now easily change the base by typing e.g. `postgis/postgis:latest`. This will also solve the [pull request for TimescaleDB](#227) as TimescaleDB is just a PostgreSQL extension.

Allow enabling services with non-standard docker images

---

app/Services/MySql.php

- Changes the MySQL service to use the `mysql/mysql-server` image by default instead of the `mysql` one, as the former seems to work well on ARM-based processors (M1)
---
This is based on a recent change made to [Laravel Sail](https://github.com/laravel/sail/pull/272)

Use mysql/mysql-server image for ARM processors

---

app/Services/MySql.php
app/Shell/DockerTags.php
tests/Feature/DockerTagsTest.php
tests/Support/IntelDockerTags.php
tests/Support/M1DockerTags.php

- Changes the MySQL service to use `mysql/mysql-server`
- Fixes the `latest` tag resolution to take into account M1 chips (`arm64` architecture) when deciding which tag to use
- Fixes not being able to connect to the container from host with root due to missing `MYSQL_ROOT_HOST` env var (https://github.com/tighten/takeout/issues/190)
---
<details>
<summary>Screenshot</summary>
</details>

MySQL on M1

---

app/Services/OpenSearch.php

Adds OpenSearch as a service.
AWS no longer has a relationship with ElasticSearch and have moved to the OpenSearch standard, forking from version 7.10.2 of ElasticSearch. This allows development directly against OS

Add OpenSearch service

---

app/Services/Minio.php

Closes #264.
However, it would probably be preferable for the domain default to be null and then to not include `MINIO_DOMAIN` in the run template at all, it wasn't immediately clear to me how that would best be accomplished, so I instead opted for a sensible default of localhost.

Set Minio domain to allow dns buckets

---

.github/workflows/run-tests.yml
composer.json

Upgrades the Laravel Zero package to v9, which drops PHP7 support. I bumped the associated dependencies to ensure we got the correct minimum versions and also bumped the tlint package to v6 to satisfy the requirements.
I was successfully able to build and run Takeout using PHP 8.1.3 after performing this upgrade.

Upgrade Laravel Zero to v9

---

app/Services/MsSql.php

Just as the title says, this enables the Microsoft SQL Server container to use a data volume just like other database services.
Command is taken straight from MS documentation: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver15&pivots=cs1-bash#use-data-volume-containers

Mssql add data volume

---

app/Commands/DisableCommand.php
app/Shell/Docker.php
app/Shell/Environment.php

Replaces #150 
Closes #112 
Re-worked #150 given some changes we've made to the `DisableContainer` command

Prompt to stop Docker in Mac, Windows, and Linux after disabling last container

---

.github/workflows/run-tests.yml

First, dropping `--ignore-platform-reqs` to fix tests for PHP 8, and then seeing if we need to make other changes to re-fix the problem it was introduced to solve: https://github.com/tighten/takeout/pull/136
Dropping `--ignore-platform-reqs` fixed Ubuntu PHP 8.0, but broke Windows again because of a missing `ext-fileinfo` extension, so next I made *only* that extension ignored, which seems have to fixed the problem.

Fix GitHub Actions tests

---

README.md
app/Commands/EnableCommand.php
app/Services/BaseService.php
composer.json
tests/Feature/BaseServiceTest.php
tests/Feature/ServiceEnableDefaultTest.php
tests/Support/FakeDockerTags.php
tests/Support/FakeService.php

- Reverts the passthrough options to be container arguments instead of docker run options (https://github.com/tighten/takeout/pull/302)
- Adds a new `--run` option to the enable command which can be used to pass any extra docker run option
---
This is how we can use this:
```bash
takeout enable mysql --run="--restart unless-stopped -e 'LOREM=IPSUM'" -- -h127.0.0.1 -usome-user
```
This will be translated to a docker command like this:
```bash
docker run --restart unless-stopped -e 'LOREM=IPSUM' {service-options} mysql -h127.0.0.1 -usome-user
```
where `{service-options}` depends on the options defined in the service class.

Adds a `--run` option to the enable command

---

app/Services/ElasticSearch.php
app/Services/OpenSearch.php

Using the search services without security is not simply a case of changing client config, the services need to be configured as well.
This makes using Opensearch and Elasticsearch without security or SSL possible. The defaults are set to secure.
Note that the opensearch change enables HTTP access, which is less troublesome than HTTPS.
The Elasticsearch change enables access without having to provide username and password like:
```
curl http://elastic:changeme@127.0.0.1:9200
```
HTTPS access on Elasticsearch is only available to paid subscriptions and requires a license key, which I dont think this tool would use.

Add prompts for security on OpenSearch and ElasticSearch services

---

.github/workflows/run-tests.yml
composer.json

- Fixes `phar` file not compatible with PHP 8.0 when pulling the Composer dependencies and building from a higher PHP version
---
issues #296

Ensure Composer dependencies are compatible with PHP 8.0

---

app/Services/Traefik.php

Adds [traefik](https://doc.traefik.io/traefik/) reverse proxy to the list of available services

Add traefik service

---

app/Services/MailDev.php

- Updated default image tag for maildev
- Changed ports used by maildev image
---
MailDev has released a new major version that has a breaking change in the ports exposed by the docker image. With this new major version they have also introduced ARM image support, helpful for us running on newer macs.

Update MailDev image tag, ports and template

---

app/Services/EventStoreDB.php

Since #154 , EventStore has improved the local DX. This PR reverts to use the latest version - which to my benefit will auto-select the arm version on my mac, love it!

EventStoredB: use latest version, pass in params for local dev

---

app/Services/MsSql.php
app/Shell/MicrosoftDockerTags.php
tests/Feature/DockerTagsTest.php
tests/Feature/MicrosoftDockerTagsTest.php

- Changes the MSSQL image from `mssql/server` to `azure-sql-edge` which seems to be one that works on both M1 and Intel-based machines.
---
Note: We have only tested that when using the new image, the container (service) is able to run on M1 machines, we didn't fully tested if this image is a full replacement of the previous one. [The issue](https://github.com/tighten/takeout/issues/293) of where this change originated from mentions [this article](https://medium.com/geekculture/docker-express-running-a-local-sql-server-on-your-m1-mac-8bbc22c49dc9) which seems to imply it's a replacement.
resolves #293

Changed the MSSQL image for one that works on M1

---

app/Commands/DisableCommand.php
app/Commands/StartCommand.php
app/Commands/StopCommand.php
tests/Feature/StartCommandTest.php
tests/Feature/StopCommandTest.php

- Adds the ability to start and stop containers by service name. Currently, to start/stop specific containers we need to pass the container ID. With this change, we get the ability to also pass the service name of such containers. This makes the start/stop commands behave closer to enable/disable.
---
Before:
```bash
takeout start 123123123
```
Now:
```bash
takeout start mysql
```
resolves #284

Improve Start and Stop DX

---

app/Services/Soketi.php

- Sets the default tag to `latest-16-alpine`, same one as Sail uses (see [here](https://github.com/laravel/sail/blob/1.x/stubs/soketi.stub)) to fix the issue described at #318 
---
Fixes #318

Set the default tag to latest-16-alpine, same one as Sail uses

---

app/Services/Buggregator.php
app/Shell/GitHubDockerTags.php
tests/Feature/GitHubTagsTest.php

- Adds [Buggregator](https://buggregator.dev/) as a tool.
---
Hat tip to @gcavanunez for pointing me to Buggregator.
Usage:
```
takeout enable buggregator
```
After answering the prompted questions (about where the web UI, the VarDumper server, the Monolog server port, and network alias), the service should run at localhost:8000 (unless you change the default port).
To start sending `dump()` calls to Buggregator, you may set the following configs on the Laravel app:
```env
VAR_DUMPER_FORMAT=server
VAR_DUMPER_SERVER=127.0.0.1:9912
```
First, on the Laravel app, require the Ray PHP client:
```bash
composer require spatie/laravel-ray --dev
```
Next, set the following configs:
```env
RAY_HOST=ray@127.0.0.1
RAY_PORT=8000
```
To send emails, you may set the following configs on the Laravel app: …

Adds Buggregator as a tool

---

README.md

- Enforce the latest version in the install command to avoid issues like #314 and #323
---
closes https://github.com/tighten/takeout/issues/323
hat tip to @cheesegrits for the suggestion [here](https://github.com/tighten/takeout/issues/314#issuecomment-1622430535).

Enforce the version in docs

---

composer.json

- Bumps the `guzzlehttp/ps7` dependency version to `^2.6`. I don't think there's a reason to stick to `^1.7`.
---
closes https://github.com/tighten/takeout/issues/279

Bump the guzzlehttp/ps7 version

---

app/Services/Typesense.php

This is my first contribution here -- please let me know if I've missed something.
- Typesense service option via Takeout
Saw [this old issue](https://github.com/tighten/takeout/issues/303) and was inspired by todays [Laravel News article](https://laravel-news.com/laravel-scout-typesense) about Typesense getting added to Scout.

Add Typesense service class

---

app/Services/MySql.php

Make use of offical mysql docker image which includes latest versions 8.2 and 8.0.35.
remove variable `$organization` will default to string `library` which is used as `$organization` when pull official images.
fix #329

fix issue #329

---

README.md

Aiming at highlighting the networking details from -> #174
- sharing that it is automatically added to a network named takeout
- Sharing the basics about how the aliasing and base aliasing works
- (optional) giving an example of how to use them in another Docker container using their aliases.
Reference issue
- #174

Add documentation for the network details

---

app/Services/MySql.php

- In https://github.com/tighten/takeout/pull/330, we reverted back to the official MySQL image. After merging that PR, I noticed that it now complains about the `--default-authentication-plugin` flag that we are setting saying it doesn't exist (from https://github.com/tighten/takeout/pull/116). I don't see that same flag being set on [Laravel Sail](https://github.com/laravel/sail/blob/1.x/stubs/mysql.stub). After testing without it, I was able to connect from my host machine, then created a sample Laravel Sail project to use the Takeout MySQL container, and it works. So we're dropping it.
- The `MYSQL_ALLOW_EMPTY_PASSWORD` flag can always be set to `1` instead of making it dynamic based on the password used.

MySQL Tweaks

---

.github/workflows/run-tests.yml

- Tweaks the CI workflow config so we only run tests on PHP 8.1, 8.2, and 8.3
- Removes `macos-11` (builds were too slow)

Tweaks workflows config

---

app/Services/MailDev.php
app/Shell/DockerTags.php
app/Shell/ElasticDockerTags.php
app/Shell/GitHubDockerTags.php
app/Shell/MicrosoftDockerTags.php
app/Shell/MinioDockerTags.php
app/Shell/MongoDockerTags.php
app/Shell/QuayDockerTags.php
app/Shell/VersionComparator.php
composer.json
tests/Feature/DockerTagsTest.php
tests/Feature/VersionComparatorTest.php

- Fixes the version sorting so we consider semver image tags higher than the other distro-specific or flavored image tag names
---
closes https://github.com/tighten/takeout/issues/337
<details>
<summary>Screenshots</summary>
</details>

Fix Images Version Sorting

---

app/Services/MariaDb.php

Heyo!
Took the logic from #115 and ported it for MariaDB. Spun up the container and I could connect with an empty password, so guessing that's all that needs to be done for testing.

Feat: Null password support for Mariadb

---

README.md
app/Commands/ShellCommand.php
app/Services/BaseService.php
app/Services/Beanstalkd.php
app/Services/Buggregator.php
app/Services/CouchDB.php
app/Services/EventStoreDB.php
app/Services/MailDev.php
app/Services/MailHog.php
app/Services/Mailpit.php
app/Services/MeiliSearch.php
app/Services/OpenSearch.php
app/Services/Soketi.php
app/Services/Traefik.php
app/Shell/Docker.php
tests/Feature/DockerTagsTest.php

- Adds a `takeout shell {service}` command to get a shell inside any container started with Takeout
- Fixes the CouchDB not starting. Looks like we now need to pass a user and password config
- Fixes the EventStoreDB. The flags that were passed no longer work
- Fixes OpenSearch not starting, the security plugin should be disabled by default
---
closes #348

Add a `takeout shell` command

---

app/Services/Ollama.php
app/Services/OpenWebui.php
tests/Feature/DockerTagsTest.php

- Adds Ollama as a tool
- Adds OpenWebUI as a tool
---
These both tools should work together. But we can use Ollama without the OpenWebUI tool (in case we're using Ollama in an application).
To run the Ollama tool (use defaults):
```bash
php ./takeout enable ollama
```
To run the OpenWebUI (use defaults):
```bash
php ./takeout enable openwebui
```
This should start Ollama at port `11434` and OpenWebUI at port `3000`. 
Open [http://localhost:3000](http://localhost:3000) (it takes a while for OpenWebUI to load), navigate to the top-right corner Admin Panel menu:
<details>
<summary>Screenshot</summary>
</details>
Then, to the Settings -> Models section, choose a model (like `llama3`), then hit the download button... this will take a while...
<details>
<summary>Screenshot</summary>
</details> …

Adds Ollama and OpenWebUI services as tools

---

app/Services/Reverb.php

- Adds a Laravel Reverb service, similar to our [Soketi](https://github.com/tighten/takeout/blob/main/app/Services/Soketi.php) offer. By default, we're using the same ports and configs as the current Soketi option, so Reverb should be a drop-in replacement for that.
---
It starts the WebSockets server on port 6001. The Pulse dashboard starts on port 9601 (same as the metrics dashboard on Soketi).
The Reverb service uses our own custom [Takeout Reverb Server](https://github.com/tighten/takeout-reverb-docker-image) Docker image, since Reverb doesn't have an official image. That image is not suited for production, but works fine for our use case here.
closes #345

Adds a Reverb Service

---

app/Services/OpenSearch.php
tests/Feature/DockerTagsTest.php

Spinning up OpenSearch running `takeout enable opensearch` using all the default prompts results in the following crash from docker:
> snapshot of logs:
```txt
Enabling OpenSearch Security Plugin
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin 
OpenSearch 2.12.0 onwards, the OpenSearch Security Plugin a change that requires an initial password for 'admin' user. 
Please define an environment variable 'OPENSEARCH_INITIAL_ADMIN_PASSWORD' with a strong password string. 
If a password is not provided, the setup will quit. 
For more details, please visit: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
OpenSearch install type: rpm/deb on Linux 6.12.10-orbstack-00297-gf8f6e015b993 aarch64
OpenSearch config dir: …
```

Add initial admin password prompt to OpenSearch service
