tighten/takeout

box.json, composer.json
This pull requests closes #65, closes #64, closes #62, closes #67, closes #41: 
1. Makes takeout have 0 dependencies.
2. Avoids global conflits
3. This pull request already contains a pre-built version with the tag `v1.0.1`, so you just have to:
```
git checkout main
git pull
git tag v1.0.1
git push --tags
```
**Note**: For next versions, before tagging a new version, you need to perform : `./takeout app:build`. 🚀
=> Adds distribution using builds

README.md
- Small typos fixed.
- The `takeout list` table now better reflects what's effectively shown in the terminal.
Thanks for this awesome package! 🙂
=> Fix 🥡 README.md

README.md
- Adding a precision regarding the multiple MySQL containers example: they must not share the same volume
- Fixed PostgreSQL spelling
=> Update 🥡 README.md

README.md, app/Services/Minio.php
Added Minio service (https://github.com/minio/minio) for a local "s3" instance.
=> Added minio service

app/Services/InfluxDB.php
Add InfluxDB service for official InfluxDB images https://hub.docker.com/_/influxdb
=> Add InfluxDB service

app/Shell/Docker.php
Helps for Linux compatibility (#37)
Co-Authored-By: Chris Kankiewicz <Chris@ChrisKankiewicz.com>
=> Update docker "is running" check to use `docker info`

README.md, app/Services/BaseService.php, app/Services/Beanstalkd.php, app/Shell/DockerTags.php, tests/Feature/DockerTagsTest.php
Also allow for images with only "latest" tag, and services with no prompts
=> Add beanstalkd

app/Services/Beanstalkd.php, app/Services/DynamoDB.php, app/Services/ElasticSearch.php, app/Services/InfluxDB.php, app/Services/MailHog.php, app/Services/MariaDb.php, app/Services/MeiliSearch.php, app/Services/Memcached.php, app/Services/Minio.php, app/Services/MsSql.php, app/Services/MySql.php, app/Services/PostgreSql.php, app/Services/Redis.php
https://symfony.com/doc/current/components/process.html#using-features-from-the-os-shell
Tip via @sinnbeck: https://github.com/tightenco/takeout/issues/37#issuecomment-688658773
=> Update all Docker Run templates to use OS-portable variable syntax

README.md
Added a bit in the FAQ's per the discussion in this issue: #109 
Take it if it's helpful, freely close this otherwise.
Thanks!
=> Add FAQ about volume persistence to README

README.md, app/Services/Mongo.php, app/Shell/MongoDockerTags.php
=> Add Mongo support

app/Commands/ListCommand.php
=> Display a message if no Takeout containers are enabled

README.md
Adds version and downloads badges to the readme.
=> Add packagist badges

.github/workflows/run-tests.yml
=> Add Linux, Windows Testing Again

README.md
=> Update docs to include enabling/disabling multiple services in one command

README.md, app/Services/Sqs.php
Add SQS support
- Default Node Host Port : 9324
- Management Http Host Port : 9325
=> Add SQS support

README.md, app/Services/Neo4j.php, tests/Feature/ServicesTest.php
Add support for [Neo4j](https://neo4j.com/)
- Default port: 7474
- Bolt access port: 7687
=> Add support for Neo4j

README.md
=> Add Sftp service on readme

app/Services/ClickHouse.php
=> Added clickhouse support

tests/Feature/DisableCommandTest.php
I have added some tests for the disable command, together with selecting things with the menu.
If the testing of menu is acceptable, then I wouldn't mind fixing the test marked `incomplete` also.
=> Add tests for disable command

app/Shell/Docker.php
Fixes issue #195 
See commits in the issue.  If I need to make any modifications, then just let me know.  Thanks!
=> Fix bug cannot stop an already stopped container

tests/Feature/DockerContainersTest.php
Ok in an attempt to be thorough and try and work on getting better at testing, I created a test that validates the fix that was merged in PR #196.  This should close issue #195.  
If you comment out the conditional that was merged already, then this new test will fail.  So, I think it is validating things correctly.
Let me know if you need me to make any changes.  Thanks!
=> Add test to validate fix for issue 195

README.md, app/Commands/HelpCommand.php, app/Commands/StartCommand.php, app/Commands/StopCommand.php
This PR adds the ability to start or stop multiple containers at once.
=> Start or close multiple containers.

app/Shell/DockerTags.php, tests/Feature/DockerTagsTest.php
Closes #207
Closes #213
Added a failing test as well.
=> Properly sort versions (closes #207 & #213)

.github/workflows/lint.yml, tests/support/MicrosoftDockerTagsFakestream.php
This pull request updates the GitHub Actions Slack Notification Package from v2 to v3.
=> Upgrade GitHub Actions Slack Notification Package

app/Services/SingleStore.php
This adds [SingleStore](https://www.singlestore.com) to the services
=> Add SingleStore

app/Services/CouchDB.php
Adds CouchDB as a database service.
https://hub.docker.com/_/couchdb
=> Add CouchDB service

tests/Feature/BaseServiceTest.php
=> Adds a test for custom docker image support

app/Services/MySql.php
=> Revert "Use mysql/mysql-server image for ARM processors"

app/Services/Category.php, app/Services/Soketi.php, app/Shell/QuayDockerTags.php
=> Add Soketi service

app/Services/Solr.php
Adds a solr service. I needed for a project myself. But I can understand if you don't want it included in the project, since it is not that popular anymore.
Still, because of the small amount (a single file) of code, the package maintainability wouldn't increase. That's why I created this PR.
=> Add Solr service

composer.lock
This fixes the issues introduced by PR #274. I forgot to commit the composer.lock file and I believe that's why we're seeing issues with the 2.0.0 build. I've included a v2.0.1 build that works, so this should just need a tag.
=> Commit composer.lock and update build

app/Services/Couchbase.php, tests/Feature/DockerTagsTest.php
Adds Couchbase to the list of database services. Confirmed Couchbase server is running locally and compiling of takeout CLI worked.
=> Add Couchbase to database services

app/Services/Traefik.php
- Fixes the default value for Traefik service (follow up of https://github.com/tighten/takeout/pull/319)
=> Fix the default config_dir value for Traefik

app/Services/Timescale.php
This adds the [Timescale](https://www.timescale.com/) service
=> Add Timescale

app/Services/PGVector.php, tests/Feature/DockerTagsTest.php
- Adds a PGVector service to make it easy to play with embeddings
---
close #342
=> Adds pgvector
